<?php

/**
 * @file
 * Aprendiendo a programar con Drupal
 * Modulo de ejemplo de un bloque con formulario Ajax
 */

 /**
  * Implements hook_menu().
  */
function blockFormAjax_menu() {
  
  $items = array();
  $items['blockFormAjax'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('blockFormAjax_form'),
    'access arguments' => array('access content'),
//    'type' => MENU_CALLBACK,
  );
  
  return $items;
}
