<?php

/**
 * @file
 * Module file for HOLA MUNDO example.
 */

/**
 * Implements hook_menu().
 */
function saludar_menu() {
	// Ruta de la página de saludo.
	$items['saludar/hola-mundo'] = array (
		 'title' => 'Saludar',
		 'page callback' => 'saludar_hola_mundo', //Función a ejecutar
		 'access callback' => TRUE, // Acceso libre
	);
	// Ruta configuración
	$items['admin/config/content/saluda'] = array (
		'title' => 'Saluda Config',
		'description' => 'Opciones saludo',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('saludar_config_form'),
		'access arguments' => array('administer site configuration'),
	);
  return $items;
}

/**
 * Function Controller saludar_hola_mundo
 */
function saludar_hola_mundo() {
	global $user;
	$usuario = user_load($user->uid);
	$fecha = time();
	$variables = array (
		'saludo' => variable_get('saludo', 'Hola Mundo!'),
		'fecha' => date('h:i:s', $fecha),
		'usuario' => $usuario,
	);
	return theme('saludar_hola_mundo', $variables);
}

/**
 * Function Controller Configuration
 */
function saludar_config_form() {
  $form['saludo'] = array (
    '#title' => 'Saludo que se muestra al usuario',
    '#type' => 'textfield',
    '#default_value' => variable_get('saludo', 'Hola Mundo!'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

function saludar_theme() {
  $templates = array (
		'saludar_hola_mundo' => array('template' => 'templates/saludar-hola-mundo',),
  );
  return $templates;
}

/**
 * Implements hook_block_info().
 */
function saludar_block_info() {
  $blocks['hola_mundo'] = array(
    'info' => 'Bloque para Hola Mundo',
    'status' => TRUE,
    'region' => 'sidebar_first',
    'visibility'=> BLOCK_VISIBILITY_LISTED,
//    'pages' => 'node/*',  // <-- Podemos limitar las páginas donde se mostrará.
  );
  return $blocks;
}

/**
 * Implementa hook_block_view().
 * Retorna una vista renderizada de un bloque.
 */
function saludar_block_view($delta = '' ) {
  switch ($delta) {
    case 'hola_mundo':
      $block['content'] = saludar_hola_mundo();
      return $block;
  }
}
