<?php

/**
 * @file
 * Module file for HOLA MUNDO example.
 */

/**
 * Implements hook_menu().
 */
function saludar_menu() {
	// Ruta de la página de saludo.
	$items['saludar/hola-mundo'] = array (
		'title' => 'Saludar',
		'description' => 'Ruta principal del hola mundo',
		'page callback' => 'saludar_hola_mundo', //Función a ejecutar
		'access callback' => TRUE, // Acceso libre
	);

 return $items;
}

/**
 * Function Controller saludar_hola_mundo
 */
function saludar_hola_mundo() {
	global $user;
	$fecha = time();
	$variables = array (
		'saludo' => variable_get('saludo', 'Hola Mundo!'),
		'fecha' => date('h:i:s', $fecha),
		'usuario' => $user,
	);
	return theme('saludar_hola_mundo', $variables);
}

/**
 * Implements hook_theme()
 */
function saludar_theme() {
  $templates = array (
		'saludar_hola_mundo' => array('template' => 'templates/saludar-hola-mundo',),
  );
  return $templates;
}