<?php

/**
 * @file
 * Aprendiendo a programar con Drupal
 * Modulo de ejemplo de Formulario
 */

function formulario_menu() {
  $items = array();
  $items['formulario-basico'] = array(
    'title' => 'Formulario Básico',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('formulario_basico'),
    'access callback' => TRUE,
    'description' => 'Formulario con validador y submit',
  );

  return $items;
}

/**
 * Formulario con validador y submit
 *
 * @see formulario_basico_validate()
 * @see formulario_basico_submit()
 * @ingroup formulario
 */
function formulario_basico($form, &$form_state) {
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('Formulario básico con validador y submit'),
  );
  $form['nombre_completo'] = array(
    '#type' => 'fieldset',
    '#title' => t('Name'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['nombre_completo']['nombre'] = array(
    '#type' => 'textfield',
    '#title' => t('Nombre'),
    '#required' => TRUE,
    '#default_value' => "",
    '#description' => "Indica aquí tu nombre",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['nombre_completo']['apellidos'] = array(
    '#type' => 'textfield',
    '#title' => t('Apellidos'),
    '#description' => t('Indica aquí tus apellidos'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['fecha_nacimiento'] = array(
    '#type' => 'textfield',
    '#title' => "Fecha de nacimiento",
    '#description' => 'Formato "YYYY"',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}


/**
 * Validation function for formulario_basico().
 */
function formulario_basico_validate($form, &$form_state) {
  $fecha_nacimiento = $form_state['values']['fecha_nacimiento'];
	$limite_inferior = date('Y') - 100;
	$limite_superior = date('Y');
  if (empty($fecha_nacimiento) || ($fecha_nacimiento <= $limite_inferior || $fecha_nacimiento >= $limite_superior)) {
    form_set_error('fecha_nacimiento', t('Indica un año entre '.$limite_inferior.' y '.$limite_superior));
  }
}



